### ISSUE TITLE
non-issue, making a library

### ISSUE THREAD

**Issue by Vortetty** [loup-brun/buttons#5]
making a library you can import into any project to easily use this from a cdn, and not have to root through the css. will be posting where to import from

**Comment by loup-brun** [comment]
Hi Vortetty, I have planned to make this easier to import – this will come when I have some free time 😉

**Comment by loup-brun** [comment]
@Vortetty see #4

**Comment by Vortetty** [comment]
ok, i may make modules for individual button types, however they will be far from perfect. i i do do this, i will post the code

**Comment by Vortetty** [comment]
you can see my progress here: https://codepen.io/vortetty/pen/OJJxYPz
